#!/usr/bin/env node
/** Static poster QA. It catches source-spec geometry/content defects, not visual defects. */
import fs from 'node:fs';
import path from 'node:path';

function args(argv){const o={};for(let i=0;i<argv.length;i++){if(argv[i].startsWith('--'))o[argv[i].slice(2)]=argv[i+1]&&!argv[i+1].startsWith('--')?argv[++i]:true;}return o;}
function main(){const a=args(process.argv.slice(2));if(a.help||!a.html){console.log('qa.mjs --html poster.html [--report qa.json]');process.exitCode=a.help?0:2;return;}const html=path.resolve(a.html);if(!fs.existsSync(html))throw new Error(`HTML not found: ${html}`);const source=fs.readFileSync(html,'utf8');const findings=[];const canvas=source.match(/name="poster-canvas" content="(\d+)x(\d+)"/);if(!canvas)findings.push({severity:'blocker',area:'canvas',detail:'Poster canvas metadata is missing.'});const width=canvas?Number(canvas[1]):null,height=canvas?Number(canvas[2]):null;const template=/<main\b[^>]*\bdata-template="true"/.test(source);if(template&&!/background-image:url\(/.test(source))findings.push({severity:'blocker',area:'template',detail:'Template mode is set but no background image is embedded in CSS.'});
 const regions=[...source.matchAll(/<div class="region"([^>]*)style="([^"]*)"[^>]*>([\s\S]*?)<\/div>/g)].map((m,i)=>{const style=m[2],get=k=>{const x=style.match(new RegExp(`(?:^|;)\\s*${k}:\\s*([\\d.]+)%`));return x?Number(x[1]):null;};return {i,left:get('left'),top:get('top'),width:get('width'),height:get('min-height'),cover:/data-covers-source="true"/.test(m[1]),text:m[3].replace(/<[^>]*>/g,'').trim()};});
 for(const r of regions){if([r.left,r.top,r.width,r.height].some(v=>v===null))findings.push({severity:'major',area:'geometry',detail:`Replacement region ${r.i+1} is missing percentage bounds.`});else if(r.left<0||r.top<0||r.width<=0||r.height<=0||r.left+r.width>100.01||r.top+r.height>100.01)findings.push({severity:'blocker',area:'geometry',detail:`Replacement region ${r.i+1} is outside the canvas.`});if(!r.text)findings.push({severity:'major',area:'content',detail:`Replacement region ${r.i+1} is empty.`});}
 for(let i=0;i<regions.length;i++)for(let j=i+1;j<regions.length;j++){const x=regions[i],y=regions[j];if([x.left,x.top,x.width,x.height,y.left,y.top,y.width,y.height].some(v=>v===null))continue;const ix=Math.max(0,Math.min(x.left+x.width,y.left+y.width)-Math.max(x.left,y.left)),iy=Math.max(0,Math.min(x.top+x.height,y.top+y.height)-Math.max(x.top,y.top));const area=ix*iy,smaller=Math.min(x.width*x.height,y.width*y.height);if(smaller&&area/smaller>0.12)findings.push({severity:'major',area:'overlap',detail:`Replacement regions ${i+1} and ${j+1} overlap by ${Math.round(area/smaller*100)}% of the smaller region.`});}
 if(template)findings.push({severity:'note',area:'template',detail:'Background/old baked-in text needs visual inspection. Static QA cannot detect seams, ghost text, or inaccurate reconstruction.'});
 const report={html,canvas:width&&height?{width,height}:null,mode:template?'template-reference':'original-design',replacementRegions:regions.length,coveredSourceRegions:regions.filter(r=>r.cover).length,findings,ok:!findings.some(f=>f.severity==='blocker'||f.severity==='major'),manualVisualReviewRequired:true,limitations:['Does not render the file or inspect image pixels.','Does not verify that source text is truly erased behind cover regions.','Does not detect optical alignment, raster blur, output color management, or font substitution.']};
 if(a.report){const p=path.resolve(a.report);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(report,null,2));}
 console.log(JSON.stringify(report,null,2));if(!report.ok)process.exitCode=1;}
try{main();}catch(e){console.error(`QA failed: ${e.message}`);process.exitCode=1;}
